version: 2

builds:
  - skip: true

changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features and updates"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999
  filters:
    exclude:
      - ^test
      - changelog
      - typo
      - Readme
      - ^Merge pull request
      - ^Merge branch
