exclude_path = [".github", ".devcontainer", "wiki", "mollie", "testdata"]
exclude = ['^https://github\.com', '^https://api\.mollie\.com/v2/']
cache = true
max_redirects = 3
require_https = true
timeout = 10
retry_wait_time = 15
verbose = "error"
no_progress = true
