version: "3"

tasks:
  build:
    desc: "Build the project using the Dockerfile go installation"
    cmds:
      - docker build -t mollie-go:latest -f Dockerfile .
    silent: true

  run:
    desc: "Run the tests using the Dockerfile go installation"
    cmds:
      - docker run --rm mollie-go:latest
    silent: true

  ci-lint:
    desc: "Run all linters used in the CI pipeline"
    cmds:
      - golangci-lint run --output.tab.path stdout -n --uniq-by-line
    silent: true

  ci-lint-all:
    desc: "Run all linters used in the CI pipeline"
    cmds:
      - golangci-lint run --output.tab.path stdout --uniq-by-line
    silent: true

  lint:
    desc: "Run the go linters"
    cmds:
      - go version
      - echo "Running go lint"
      - golint ./...
      - echo "Running go vet"
      - go vet ./...
    silent: false

  test:
    desc: "Run tests using the Dockerfile go installation"
    cmds:
      - task: run
    silent: false

  test-local:
    desc: "Run tests using a local go installation"
    cmds:
      - go test -failfast ./... -coverprofile cover.out
    silent: false

  coverage:
    desc: "Run tests and generate a default coverage report"
    cmds:
      - go tool cover -func=cover.out
    silent: false

  cover-report:
    desc: "Run tests and generate coverage report in HTML format"
    cmds:
      - go tool cover -html=cover.out
    silent: false

  clean:
    desc: "Verify and tidy go modules"
    cmds:
      - go mod verify
      - go mod tidy
    silent: false

  update-docs:
    desc: "Update the generated docs for the mollie package"
    cmds:
      - gomarkdoc --output docs/README.md ./mollie
      - git add --all
      - "git commit --message 'chore(docs): update generated docs'"
    silent: false

  sub-pkg-docs:
    desc: "Update the generated docs for the sub-packages"
    cmds:
      - gomarkdoc ./pkg/connect > docs/pkg/connect/README.md
      - gomarkdoc ./pkg/idempotency > docs/pkg/idempotency/README.md
      - gomarkdoc ./pkg/pagination > docs/pkg/pagination/README.md
    silent: false
