concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: testing

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/release.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/release.yml"
jobs:
  tests:
    permissions:
      contents: read
    strategy:
      matrix:
        go: [1.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # 6.5.0
        with:
          go-version: ${{ matrix.go }}
      # Get values for cache paths to be used in later steps
      - id: cache-paths
        run: |
          echo "go-cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod-cache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Cache go modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ${{ steps.cache-paths.outputs.go-cache }}
            ${{ steps.cache-paths.outputs.go-mod-cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - run: go test -failfast -timeout 5m ./...
